name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "DeterminateSystems/nix-installer-action@main"
        env:
          FLAKEHUB_TOKEN: ${{ secrets.FLAKEHUB_TOKEN }}
        with:
          flakehub: true
      - uses: "DeterminateSystems/flakehub-push@main"
        env:
          FLAKEHUB_TOKEN: ${{ secrets.FLAKEHUB_TOKEN }}
        with:
          name: "Lobanokivan11/nix-snapd"
          rolling: true
          flakehub: true
          visibility: "public"
